/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjetsIndexRouteImport } from './routes/projets/index'
import { Route as ProjetsSlugRouteImport } from './routes/projets/$slug'
import { Route as BlocsSlugBlockIdRouteImport } from './routes/blocs.$slug.$blockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsIndexRoute = ProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/projets/$slug',
  path: '/projets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocsSlugBlockIdRoute = BlocsSlugBlockIdRouteImport.update({
  id: '/blocs/$slug/$blockId',
  path: '/blocs/$slug/$blockId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/projets/': typeof ProjetsIndexRoute
  '/blocs/$slug/$blockId': typeof BlocsSlugBlockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/projets': typeof ProjetsIndexRoute
  '/blocs/$slug/$blockId': typeof BlocsSlugBlockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/projets/': typeof ProjetsIndexRoute
  '/blocs/$slug/$blockId': typeof BlocsSlugBlockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/projets/$slug'
    | '/projets/'
    | '/blocs/$slug/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/projets/$slug'
    | '/projets'
    | '/blocs/$slug/$blockId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/projets/$slug'
    | '/projets/'
    | '/blocs/$slug/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  ProjetsSlugRoute: typeof ProjetsSlugRoute
  ProjetsIndexRoute: typeof ProjetsIndexRoute
  BlocsSlugBlockIdRoute: typeof BlocsSlugBlockIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/': {
      id: '/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof ProjetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/projets/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocs/$slug/$blockId': {
      id: '/blocs/$slug/$blockId'
      path: '/blocs/$slug/$blockId'
      fullPath: '/blocs/$slug/$blockId'
      preLoaderRoute: typeof BlocsSlugBlockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  ProjetsSlugRoute: ProjetsSlugRoute,
  ProjetsIndexRoute: ProjetsIndexRoute,
  BlocsSlugBlockIdRoute: BlocsSlugBlockIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
